name: Java Application

on:
    # push:
    # pull_request:
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            
            - name: Setup Java JDK 11
              uses: actions/setup-java@v3.12.0
              with:
                java-version: '11'
                distribution: temurin
                cache: maven

            - name: Build with Maven
              run: |
                  mvn package -DskipTests

            - name: upload Build Artifacts
              uses: actions/upload-artifact@v3.1.2
              with:
                name: myArtifact
                path: ./target/*.war

            - name: upload Build Artifacts
              uses: actions/upload-artifact@v3.1.2
              with:
                name: myArtifact
                path: ./target/*.war

    ghcr:
        name: Build and Pushing image to GHCR
        runs-on: ubuntu-latest
        needs: Build

        steps:
            - name: Checkout the Source Code
              uses: actions/checkout@v3

            - name: Build and Push the image to GHCR
              run: |
                docker login -u $GITHUB_REPOSITORY_OWNER -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
                docker build . -t ghcr.io/canarysplayground/myshuttle:latest           
                docker push ghcr.io/canarysplayground/myshuttle:latest
