name: Java Application

on:
    # push:
    # pull_request:
    pull_request_review:
        types: [submitted]
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest
        outputs:
            set_date: ${{ steps.set_date.outputs.DATE }}
        steps:
            - name: Date variable
              id: set_date
              run: |
                  echo "DATE=$(date +"%Y%m%d")" >> $GITHUB_OUTPUT
                  
            - uses: actions/checkout@v3
            
            - name: Setup Java JDK 11
              uses: actions/setup-java@v3.12.0
              with:
                java-version: '11'
                distribution: temurin
                cache: maven

            - name: Build with Maven
              run: |
                  mvn package -DskipTests

            - name: upload Build Artifacts
              uses: actions/upload-artifact@v3.1.2
              with:
                name: "myArtifact_${{ steps.set_date.outputs.DATE }}"
                path: ./target/*.war

    ghcr:
        name: Build and Pushing image to GHCR
        environment: 'GHCR'
        runs-on: ubuntu-latest
        needs: Build

        steps:
            # - name: Version variable
            #   id: set_version
            #   run: |
            #       echo "VERSION=$(date +"%Y%m%d"_+"%s")" >> $GITHUB_OUTPUT

            - name: version
              run: |
                  echo "VERSION=$(echo $(date +%Y%m%d_%H%M))" >> $GITHUB_ENV
              
            - name: Downloading the artifacts
              uses: actions/download-artifact@v3
              with:
                  name: "myArtifact_${{needs.Build.outputs.set_date}}"
                  path: ./target

            - name: Checkout the Source Code
              uses: actions/checkout@v3

            - name: Build and Push the image to GHCR
              run: |
                docker login -u $GITHUB_REPOSITORY_OWNER -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
                docker build . -t ghcr.io/canarysplayground/myshuttle:${{ env.VERSION }}     
                docker push ghcr.io/canarysplayground/myshuttle:${{ env.VERSION }}
